//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string fam { get; set; }
        public string name { get; set; }
        public System.DateTime daterj { get; set; }
        public decimal oklad { get; set; }
        public System.DateTime daterab { get; set; }
        public string doljn { get; set; }
        public string tel { get; set; }
        public string adres { get; set; }
        public int id_graf { get; set; }
    }
}
