//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursovMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zarp
    {
        public int Id { get; set; }
        public string fam { get; set; }
        public decimal prem { get; set; }
        public decimal nach { get; set; }
        public decimal uder { get; set; }
        public decimal itog { get; set; }
        public int id_graf { get; set; }
        public int id_sotr { get; set; }
        public string mes { get; set; }
        public string otpus { get; set; }
    }
}
